---
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - /var/opt/changedetection:/datastore
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000
      - BASE_URL=https://cd.dokploy.dota.com
      - USE_X_SETTINGS=1
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      browser-sockpuppet-chrome:
        condition: service_started
    networks:
      - changedetection-net

  browser-sockpuppet-chrome:
    hostname: browser-sockpuppet-chrome
    image: docker.io/dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    networks:
      - changedetection-net

networks:
  changedetection-net:
    driver: bridge
